spring:
    session:
      store-type: redis
    application:
        name: spring_session_with_redis
#    security
    security:
        user:
            name: user
            password: 123
#    redis
    cache:
        redis:
            time-to-live: 86400
    data:
        redis:
            host: redis
            port: 6379
server:
    port: 8090