spring:
    session:
      store-type: redis
    application:
        name: spring_session_with_redis
#    security
    security:
        user:
            name: user
            password: 123
#    redis
    data:
        redis:
            host: 127.0.0.1
            port: 6379
server:
    port: 8090