spring:
    session:
        store-type: redis
    application:
        name: spring_session_with_redis
#    security
    security:
        user:
            name: user
            password: 123
    cache:
        type: redis
        redis:
            cache-null-values: false
            time-to-live: 60
#    redis
    data:
        redis:
            host: redis
            port: 6379
server:
    port: 8090