spring:
    application:
        name: spring_session_with_redis
    security:
        user:
            name: user
            password: 123

    data:
        redis:
            host: redis
            port: 6379
server:
    port: 8090