name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
permissions:
      contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Build with Gradle Wrapper
      run: ./gradlew build
  # deploy:
  #   needs: build
  #   runs-on: self-hosted
  #   steps:
  #     - name: Checkout source
  #       uses: actions/checkout@v4
  #     - name: Login to Docker Hub
  #       run: echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
  #     - name: Pull and Start services using Docker Compose
  #       run: |
  #         docker-compose down
  #         docker-compose pull
  #         docker-compose up -d
