# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
        # Gradle ni GitHub ishlariga moslashtirish, yuklab olingan bog'liq foydalanishni o'zgartirish.
        # Ko'rish uchun: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Gradle ni sozlash
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Gradle Wrapper bilan tozalash va tuzish (testlarsiz)
        run: ./gradlew clean build -x test
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build Docker Image
        run: docker build -t bobur7761/spring_session .
      - name: Publish Docker Image
        run: docker push bobur7761/spring_session:latest
  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Bog'liqlar uchun dependensiyalar grafigini yaratish va topshirish uchun, barcha loyihaning dependensiyalariga Dependabot xabarnomalarini yoqish.
    # Ko'rish uchun: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
    - name: Dependensiyalar grafikini yaratish va topshirish
      uses: gradle/actions/dependency-submission@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
      - name: Pull and Start services using Docker Compose
        run: |
          docker-compose down
          docker-compose pull
          docker-compose up -d